### PR TITLE
Replace ontology.iedb.org code

### LINKED ISSUE #46: Update ontology.iedb.org
The ONTIE/SoT website is at <https://ontology.iedb.org/>. It's currently implemented using <https://github.com/knocean/knode>, and it doesn't work very well. I'd like to replace it using <https://github.com/ontodev/gizmos>.

There are two main components:

1. ONTIE term list: this can be improved to a Gizmos tree with search
2. SoT resources: this should use Gizmos export

If possible, I'd like the [REST API](https://github.com/IEDB/ONTIE/blob/master/doc/api.md) to continue to work, which means that the tests here should continue to pass: <https://github.com/IEDB/ONTIE/tree/master/test>. I don't care about the Term Submission section at the end of the API doc.

### PR DESCRIPTION
**Pull request by beckyjackson**
I have not yet added in support for `POST` requests. All the API  calls in the docs should still work (I had to update the JSON one). I commented out `POST` tests for now but I will fix that when I implement it.

Resolves #46

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Still to do, implement "POST instead of GET" from `doc/api.md`. Don't bother with "Term Submission".

**Comment by jamesaoverton** [comment]
The `recognized` column is being dropped but it had a purpose: It would say whether we have any record of the CURIE/IRI at all, whether or not it's current or has been obsoleted or replaced. Can we keep that functionality?

**Comment by beckyjackson** [comment]
Yeah - we could, but it would require some post-processing steps after `gizmos.extract`. It shouldn't make it any slower, though, since it's just string manipulation...

**Comment by beckyjackson** [comment]
Actually, it might be tricky for the HTML exports (which show the pages), but do we need `recognized` for that? I don't think so... Easy for the TSV though.

**Comment by beckyjackson** [comment]
OK, I've added this to the TSV output

**Comment by jamesaoverton** [comment]
This will get reworked using code from the OBI demo.

**Comment by jamesaoverton** [comment]
This is working for me now, but there's a bunch of merge conflicts. I don't think we'll end up merging this, but it's useful for now, so let's leave it open.

**Pull request closed without merging**
