### PR TITLE
ONTIE 2020 Update

### LINKED ISSUE #23: Write script to "report" on tables
This script should run some ROBOT report checks like annotation whitespace, duplicate labels, duplicate definitions, etc. over all the templates and return a standardized problems table like the one described in https://github.com/ontodev/robot/issues/712

Try python first, but if it's very slow, we will use SQLite for this.

This will go in one big branch for all the work hooking ONTIE up to DROID.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #23

I moved the old scripts to an "obsolete" folder, but I think we can get rid of them entirely? Let me know if we should keep them instead.

I tested `report` with COGS and it works as I would expect it to, but I haven't done much testing to try and break it (yet).

This isn't integrated into any particular workflow yet, but it creates a `build/problems.tsv` table. Right now, this doesn't have any `sys.exit(1)` clause because I figure we want to first integrate it with COGS, so we don't want the `Makefile` workflow exiting.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This looks good, except for one thing: the value of "fix" should not be instructions for fixing the problem, it should be a valid value. So if the rule is "no trailing whitespace" and the value is "foo   " then the value of "fix" would be "foo", with the trailing whitespace removed. For most (but not all) of these rules, we should be able to offer a valid value derived from the invalid value.

Eventually we can provide the user with a tool for applying all our automatically generated fixes, and then all the relevant problems will be fixed.

**Comment by jamesaoverton** [comment]
One more thing: The instructions that are currently provided for "fix" are useful. We could keep them, maybe in a new column. But I really want to include a suggested fix (valid value) whenever possible.

**Comment by beckyjackson** [comment]
Gotcha! So the "fix" should be blank for things like duplicate/multiple definitions, etc... since we can't really recommend an automated fix?

**Comment by jamesaoverton** [comment]
Yes

**Comment by beckyjackson** [comment]
OK - that's updated!

**Pull request merged**
