### PR TITLE
Updates to disease classes

### PR DESCRIPTION
**Pull request by beckyjackson**
Updates:
- Moved disease tree build to arborist
- Added manual subClassOf definitions for DO classes to keep structure (`ontology/manual.tsv`)
- Added more external DO classes (`ontology/external.tsv`)
- Renamed ONTIE:0003424 from ‘asymptomatic infection’ to ‘infection without disease’
- Created ‘health host status’ (ONTIE:0003542) class to group major disease-related classes:
    - ONTIE:0003423 (healthy)
    - ONTIE:0003424 (infection without disease)
    - DOID:4 (disease)
- Created ‘additional diseases by category’ (ONTIE:0003542) to group other DO classes
- Assigned IEDB-specific labels to some DO classes
- Fixed typo for ONTIE:0003441 label ‘sensorineural hearing loss’

### CODE REVIEW

**Comment by jamesaoverton** [comment]
There are so many external DO terms now, maybe MIREOT `--branch-from-terms` would be better?

**Comment by beckyjackson** [comment]
Wouldn't that include everything, since `DOID:4` (disease) is included in the list? We could just import the whole disease tree, but that seems like overkill.

**Comment by jamesaoverton** [comment]
Ok, so we don't branch from `DOID:4`, but aren't there some other branches that would simplify things?

**Comment by beckyjackson** [comment]
Here's a comment from Randi:
> we do not want any terminal node if it was not in the needed by iedb list & if there are no children used by the iedb, we do not want the whole branch.

I can try and review what we have, but I think if we did branches, it might end up including things that aren't needed by IEDB which it looks like we want to avoid.

**Comment by jamesaoverton** [comment]
Ok, no branches then.

**Comment by beckyjackson** [comment]
I need to add in some disease grouping nodes, so I'd like to wait to merge this until #14 is merged.

**Pull request merged**
