### PR TITLE
Improve DROID workflow

### LINKED ISSUE #33: Better table comparison (DROID)
Improve step 3 (compare) to only be one line. This will generate an HTML page that has all the daffs on it in different tabs. We will use Bootstrap tabs to lay out the diffs like the Google Sheet. Maybe tabs with changes are a different color?

If there are no differences in a sheet, display a message that says "no differences".

### LINKED ISSUE #34: Improve "results" wording (DROID)
The wording in step 5 (results) is a little confusing. Make it more clear and maybe remove some references to the OWL files (just one step to "Download OWL" instead)?

We should use a verb first to state what the link is doing.

### LINKED ISSUE #35: Add extra sections to workflow (DROID)
Based on MRO workflow:
image

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #33:
* Added a new "diff" page for the tables that displays each diff on a tab.

Resolves #34:
* Removed the ROBOT diff entirely (I think it's too difficult to read, but I can put it back in if we think it's worth reviewing... I think the table diffs are enough) and reworded the other "result" options to be clearer - see below

Resolves #35: See screenshot below

image

### CODE REVIEW

**Comment by beckyjackson** [comment]
Side note, I use the `lxml` module to parse the HTML here and that needed to be added to requirements.

I'm afraid to parse HTML with regex, but I really only need everything between the `<body>` tags. Thoughts @jamesaoverton ? Is there a way to get `daff` to print the HTML without headers?

---

I reworked it with regex and removed `lxml` but parsing HTML with regex still scares me. It seems to work OK here...

**Comment by jamesaoverton** [comment]
Looks like the `daff` command line tool has a `daff render --fragment` option: https://github.com/paulfitz/daff#the-program

**Comment by beckyjackson** [comment]
Thanks! I had to edit the CSS a bit but that worked perfectly.

**Review by jamesaoverton — APPROVED** [review]
This is ready to merge.

Once these DROID issues are resolved then I think we can ask Randi to use DROID for ONTIE: https://github.com/ontodev/droid/milestone/1

**Pull request merged**
